name: segmentation-analysis

channels:
  - nvidia
  - conda-forge
  - defaults
  - pytorch
  - fvcore
  - iopath
  - pytorch3d

dependencies:
  - python=3.8
  - ipykernel
  - cudatoolkit=11.3
  - cudnn=8.2
  - cupti=11.3
  - cuda-nvcc
  - pytorch::pytorch=1.11.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch3d::pytorch3d=0.7.0
  - ffmpeg
  - nodejs
  - pip
  - pip:
    - matplotlib
    - pandas
    - seaborn
    - ipywidgets
    - rich
    - scikit-learn
    - albumentations
    - opencv-python-headless
    - opencv-python
    - segmentation_models_pytorch
    - jupyter
    - shapely